### ISSUE TITLE
long code blocks break width on mobile devices

### ISSUE THREAD

**Issue by sparky005** [wangonya/flexible-gatsby#10]
Hello! I've found an issue that I can't figure out how to solve on my own. If you add a code block with a sufficiently long line, it will break the width on mobile devices. I added a long line to the welcome post and created a PR here https://github.com/wangonya/flexible-gatsby/pull/9 to demonstrate. If you open the build link on a mobile device, you should see that the width is broken

**Comment by sparky005** [comment]
Hey @wangonya, unfortunately it looks like I'm still hitting this issue on my site using this starter. Not sure if I'm not incorporating the fix right or if I'm doing something else wrong. 

Take a look at [this page](https://deploy-preview-1--vigilant-jang-2bf33e.netlify.app/predicting-bitcoin-price-using-metcalfes-law/) on my site, on a very narrow screen or on your phone. You'll see the width looks wrong. [This page](https://deploy-preview-1--vigilant-jang-2bf33e.netlify.app/netlify-test/), on the other hand, which is the same post but with the longer code blocks replaced with shorter lines, renders ok.

Am I doing something wrong or is there another fix needed?

**Comment by wangonya** [comment]
Looks like another fix is needed. Posts are responsive when it's only text but break when other elements are added in. Looking at your post, I'm not sure if it's still the code that's breaking the width or the table. I'll investigate some more when I get the time. Shouldn't be too hard to fix.

**Comment by wangonya** [comment]
Seems it's still the code that's breaking the width - specifically the long continuous lines like `get_data('https://api.blockchain.info/charts/estimated-transaction-volume-usd?timespan=all&format=json')`. I'm thinking the css doesn't know where/how to break/wrap this since it doesn't have any spaces.

I'll have to find a way to make code blocks scrollable horizontally when they exceed the page width instead of wrapping.

**Comment by sparky005** [comment]
Ahh, yeah, that makes sense! Hard to know where to wrap without spaces. [Here is the same post on my old Pelican blog](https://sparky005.com/predicting-bitcoin-price-using-metcalfes-law.html), which uses horizontally-scrolling code blocks like you suggested. Just linking it here in case it's helpful to see the two side by side.

**Comment by wangonya** [comment]
I've actually narrowed it down to just one place in the css that the issue is coming from.  The styling for the `content-box` class.

CSS isn't really my thing so it's a lot of trial and error at this point 😅 but I'm making progress

**Comment by sparky005** [comment]
I would offer to help but I'm terrible at anything frontend related. I'm trying to learn more right now actually. I really appreciate all your help here!

**Comment by wangonya** [comment]
Well, this was way harder to deal width than I initially imagined, but I think I've got it now.

**Comment by sparky005** [comment]
Amazing! Working on my site too. Thanks so much!!!
