### ISSUE TITLE
How to enable tag function

### ISSUE THREAD

**Issue by bebenosuke** [wangonya/flexible-gatsby#2]
Hi, how can I enable tag function to gather same category pages? I think we can use tag to display in footer but it is not worked to combine pages.

p.s.  this blog template is so nice and I decided to use it. thanks!

**Comment by wangonya** [comment]
Hi @bebenosuke. We don't have that functionality for now. I think it'll be useful so I'll work on it and push an update as soon as I can.

**Comment by wangonya** [comment]
I think it's a fairly simple thing to do so I've added the `good first issue` label to open it up to contributors. If anyone is able to do this before I do, I'll be happy to merge it.

**Comment by wangonya** [comment]
@bebenosuke all done. You can check it out 😉.

**Comment by bebenosuke** [comment]
@wangonya , wow thanks, this is what I want!
