### ISSUE TITLE
Consider a packages update, gatsby develop sometimes failes

### ISSUE THREAD

**Issue by elciopa** [wangonya/flexible-gatsby#4]
I would like to suggest you a `npm update` of your project. 

I had some "hangs" while running the `gatsby develop` command. In particular when I create a new post, the `gatsby develop` task was hanging at the line 

> Build manifest and related icons...

So i decided to run an npm update. Many packages have been upgraded and now it seems to work pretty well. 
Anyway thanks for this project and your effort.

**Comment by wangonya** [comment]
Thanks for the heads up. Sure, I haven't updated things in a while. I'll get to it soon as I can.

**Comment by wangonya** [comment]
Fixed!
