### ISSUE TITLE
How to change the favicon?

### ISSUE THREAD

**Issue by sparky005** [wangonya/flexible-gatsby#6]
Hey, terrific theme! I'm starting to build a site around it but I can't quite figure out how to change the favicon. Is there an easy way to do it?

**Comment by sparky005** [comment]
Of course, mere minutes after I post this question, I figure out how to do it. For anybody else that comes looking, edit the `gatsby-config.js` file on line 62 to point to the path of your new favicon. https://github.com/wangonya/flexible-gatsby/blob/master/gatsby-config.js#L62

**Comment by KlausDevWalker** [comment]
Thanks for tell us that! I wasn't worrying about the favicon right now but that was a question I was about to ask hahaha
